### ISSUE TITLE
Custom Nameserver

### ISSUE THREAD

**Issue by nirvash21** [NETLINK/Blesta-Namesilo#10]
Hi,

It could be perfect if client can register his/her custom nameserver. :)

Sincerely,
Ahmad

**Comment by julianmatz** [comment]
Do you mean vanity nameservers?

**Comment by nirvash21** [comment]
I mean Child Host, etc. Because I can't see it in the menu :)

**Comment by julianmatz** [comment]
This one?
https://www.namesilo.com/api_reference.php#addRegisteredNameServer

**Comment by neonardo1** [comment]
I'd imagine that's what he means.  I'd like to see this as well.

**Comment by neonardo1** [comment]
I have a working copy of code to do this.  I'm working on cleaning it up before submitting a pull request.
