### ISSUE TITLE
Manage DNSSEC Records

### ISSUE THREAD

**Issue by johnmcc5** [NETLINK/Blesta-Namesilo#22]
Currently, users cannot manage DNSSEC records through the module.

Perhaps there should be a DNSSEC tab in the management actions (somewhat like the "Register Nameservers" tab). This would allow clients to set up their own DNSSEC records, without having to request an admin to do it.

**Comment by neonardo1** [comment]
Looking at the API docs this shouldn't be terribly hard to implement.

**Comment by neonardo1** [comment]
Is something like this what you had in mind?

![shot-2018-04-09-17 34 33](https://user-images.githubusercontent.com/8390543/38526534-5aefb4c8-3c1c-11e8-8cda-1b2e3848ceff.png)

**Comment by johnmcc5** [comment]
You nailed it! That's exactly what I was thinking.

**Comment by neonardo1** [comment]
Ok.  The list/add logic is mostly worked out on the admin interface and the client is just a re-themed version of the same thing.

It looks like the API wants all of the information passed back in for a deletion so I need to think on the best way to get all of that data back to the API securely.

**Comment by neonardo1** [comment]
Would you be willing to help test this?  I've got a workable admin side to this in this branch:

https://github.com/knownhost/Blesta-Namesilo/tree/dnssec

**Comment by johnmcc5** [comment]
Sorry, I didn't get a chance to look at this until now.

I see that 1.8.2 has been released with support for DNSSEC, would you still like me to test your branch?

**Comment by neonardo1** [comment]
You can just update to 1.8.2 :)

Let me know if you find any issues.

**Comment by johnmcc5** [comment]
The styling appears to be off on the client side. The admin side is working fine, however.

<img width="2150" alt="formatting" src="https://user-images.githubusercontent.com/22429081/38712322-7028b12a-3e90-11e8-8cdf-c4435bacf360.png">

**Comment by neonardo1** [comment]
Ah sure enough.  I developed this in a custom theme and didn't check it against stock.  I should be able to straighten this out tomorrow.

Are you in a custom theme or stock with a different color?  Your page width looks awfully small.

**Comment by johnmcc5** [comment]
Okay, sounds good.

It's the stock theme with a different color. I also was using a laptop when taking the screenshot, but it happens regardless of my screen size.

**Comment by neonardo1** [comment]
It's good down to about 680px in width.  If the page is smaller than that the issue occurs.  The content simply won't shrink down to the minimum width that the parent container has set.  I'm not totally sure how to fix this yet, responsiveness isn't my forte.
