### ISSUE TITLE
Error when accessing the DNSSEC Tab in Admin

### ISSUE THREAD

**Issue by julianmatz** [NETLINK/Blesta-Namesilo#28]
Tag 1.8.3
`Undefined property: stdClass::$ds_record`

![03-05-2018 13-36-07](https://user-images.githubusercontent.com/1578450/39576857-840a094e-4ed7-11e8-88ec-8a76e18d36a4.png)

**Comment by neonardo1** [comment]
What do the module logs look like?  I'm not able to recreate this.  An unexpected or invalid API response could explain this though.

![shot-2018-05-03-08 13 44](https://user-images.githubusercontent.com/8390543/39578528-ffc6ff20-4ea9-11e8-939d-2ffafcb873ae.png)

**Comment by julianmatz** [comment]
Hi Jonathan. No log entries. Looks like a fatal PHP error. Below is a stack trace.

For me, the $ds object returns the following:
`stdClass::__set_state(array( 'code' => '300', 'detail' => 'You have not created any DS records for this domain yet.', ))`

So, in this object, there is no ds_record property, hence the error.

```
Undefined property: stdClass::$ds_record on line 1852 in /home/public_html/blesta/components/modules/namesilo/namesilo.php 

Printing Stack Trace: 
#0 [internal function]: UnknownException::setErrorHandler(8, 'Undefined prope...', '/home/...', 1852, Array)
#1 /home/public_html/blesta/vendors/monolog/monolog/src/Monolog/ErrorHandler.php(164): call_user_func(Array, 8, 'Undefined prope...', '/home/...', 1852, Array)
#2 /home/public_html/blesta/components/modules/namesilo/namesilo.php(1852): Monolog\ErrorHandler->handleError(8, 'Undefined prope...', '/home/...', 1852, Array)
#3 /home/public_html/blesta/components/modules/namesilo/namesilo.php(1323): Namesilo->manageDnssec('tab_dnssec', Object(stdClass), Object(stdClass), Array, Array, Array)
#4 /home/public_html/blesta/app/controllers/admin_clients.php(5329): Namesilo->tabDnssec(Object(stdClass), Object(stdClass), Array, Array, Array)
#5 /home/public_html/blesta/vendors/minphp/bridge/src/Lib/Dispatcher.php(143): AdminClients->serviceTab()
#6 /home/public_html/blesta/index.php(21): Dispatcher::dispatch('/admin/clients/...')
#7 {main}
```

**Comment by neonardo1** [comment]
Haven't forgotten about this.  Once Blesta releases 4.3 I have some things to add/adjust anyway so that's likely when I'll make my next commits and fix this since this only impacts admins.
