### ISSUE TITLE
Unable to register new domains in 1.8.3

### ISSUE THREAD

**Issue by julianmatz** [NETLINK/Blesta-Namesilo#29]
When trying to register a new domain in v1.8.3 through the admin back-end, the following error appears:
**Domain transfers require an EPP code to be entered.**

This happens whether Use Module is on or off.

**Comment by neonardo1** [comment]
I'm going to do my best to work on a build tomorrow to address this and the other open issues if I can resolve them pretty quickly.

**Comment by julianmatz** [comment]
This should be fixed with the latest push, but there seems to be another problem, which I think maybe Blesta related.

https://www.blesta.com/forums/index.php?/topic/11412-unable-to-register-domain-from-back-end/
