### ISSUE TITLE
Production Site

### ISSUE THREAD

**Issue by nightstryke** [NETLINK/Blesta-Namesilo#38]
@NETLINK Should I use 1.8.4 for a Blesta install with the latest version on a production site or should I download from the github master and use that instead??

**Comment by julianmatz** [comment]
Hi @nightstryke I think it's safe to use the Master. I'm using Master in production. Any issues, just raise them here and we'll look into them ASAP.

**Comment by nightstryke** [comment]
@julianmatz Alright, Thanks!
