### ISSUE TITLE
Duplicate module use?

### ISSUE THREAD

**Issue by buddizer** [NETLINK/Blesta-Namesilo#5]
Under the domain service there's two "use module" options. Should the one where you can select active, suspend, etc. be the only one needed apart from the upgrade/downgrade options?

![screenshot 2015-06-21 13 57 20](https://cloud.githubusercontent.com/assets/10159765/8273155/95137728-181d-11e5-877e-4a0cb172b789.png)

**Comment by julianmatz** [comment]
These sections are actucally part of Blesta core, not the module. But I have added an option under "Namesilo Options" to manually renew a domain name.
