### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by itocinc** [NETLINK/Blesta-Namesilo#6]
I'm not a developer but have suggestions.
- TLD syncing.
  -Name server Management

**Comment by julianmatz** [comment]
Hi itocinc! Can you elaborate on what you mean exactly?

**Comment by itocinc** [comment]
Hi Julianmatz, sorry for the late reply. Busy time of year with the Holidays and all.  I guess what I mean is if a new TLD is added by Namesilo, the module would automatically sync it. For example, when Namesilo began offering .xyz domains, the namesilo-blesta files had to be manually edited in order to offer .xyz domains through the Namsilo blesta app. It would be nice if the extensions would sync so that any new extension added by Namsilo would sync with the namesilo-blesta app automatically (or by cron)  --hope this is clear.  If not I'll try again  : )   Happy Holidays to you!

**Comment by julianmatz** [comment]
No worries, it was very busy for me also. I'm just settling back in now! Yes, that makes sense, and I'll look into that as soon as I get a chance.

**Comment by nomadturk** [comment]
As a suggestion,

Along with an updated list of TLD's, can I suggest sending User information to Namesilo as Registrant Information?
Or is it possible to do so?
