### ISSUE TITLE
Can not use Sandbox mode

### ISSUE THREAD

**Issue by nomadturk** [NETLINK/Blesta-Namesilo#8]
When I try to enable Sandbox mode, I'm greeted by an Invalid API key error message.
Without Sandbox mode, it works. At least I can query domains. 
But I can't enable sandbox mode either with my original key, a dummy key or just leaving key value empty.

**Comment by julianmatz** [comment]
Hi @nomadturk 
You need to enter a valid sandbox API key and associated email address. To obtain a sandbox API key, you need to contact Namesilo.
![17-03-2017 00-11-32](https://cloud.githubusercontent.com/assets/1578450/24023798/8ea1e064-0aa6-11e7-8dd0-e1cdb8cb91e2.png)
