### ISSUE TITLE
Still an active project?

### ISSUE THREAD

**Issue by mrrsm** [NETLINK/Blesta-Namesilo#9]
Just wondering if this is project is still active.  I am planning on using namesilo with blesta and this module mostly works for my needs.  I plan on contributing back if my changes will be merged otherwise I will have to run a fork of this.

**Comment by fossxplorer** [comment]
+1 @mrrsm i'm considering a move from WHMCS to blesta and Namesilo support is a must for me :)

**Comment by mrrsm** [comment]
@fossxplorer I am fairly confident that this module works for the basic functions such as whois/nameserver management/transfers/etc.  I am hoping to improve it to make my life easier until blesta refactors their domain management stuff. Things like automatically getting the available tlds rather than hard coding them in for a start.  The next task is getting the whois privacy stuff worked in.  Finally I want to add the ability to manage DNS from within blesta if possible.

**Comment by fossxplorer** [comment]
@mrrsm Thanks for you reply!
It seems Blesta staff is working the domain mgmt, but there is no ETA. Let's hope it arrives soon. 
Regardless of that, we still can't use this module with e.g .cloud etc. 
Have you made any improvents to this module?

**Comment by mrrsm** [comment]
Yes, I have made some changes mainly for pulling all the domains they support. I have a public fork of this on github with my changes.  I plan on revamping it once the domain changes in Blesta have happened.

**Comment by julianmatz** [comment]
All contributions to this project are appreciated and considered.
